# boostrap存放
# 1. 不能放进nacos的内容

---
spring:
  application:
    name: license-server

---
# 端口和上下文
server:
  port: 8080
  servlet:
    context-path: /license

---
# 数据源设置
spring:
  datasource:
    url: "jdbc:mysql://47.106.205.211:3306/license?useSSL=false&serverTimezone=GMT%2B8&useLocalSessionState=true&useAffectedRows=true"
    username: root
    password: my-secret-ab
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

---
# druid 设置
spring:
  datasource:
    druid:
      maxWait: 60000
      filters: stat,wall
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      testWhileIdle: true
      testOnBorrow: false
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 60000
      testOnReturn: false
      initial-size: 5
      maxActive: 20
      # druid.stat.mergeSql=true 会导致报错, 但不影响功能 https://github.com/alibaba/druid/issues/1956
      connectionProperties: druid.stat.mergeSql=false;druid.stat.slowSqlMillis=5000
      min-idle: 5
      validationQuery: SELECT 1
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
        enabled: true
      stat-view-servlet:
        allow: 127.0.0.1,*
        deny: 192.168.1.73
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 123456

---
# jackson 序列化
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null

---
# mybatis
mybatis:
  mapper-locations: classpath:**/*Mapper.xml
  type-aliases-package: org.dormi.learn

---
# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

---
# logger
logging:
  level:
    org.springframework: info
    org.springframework.test: info
    org.dormi.learn: debug
    org.dormi.learn.infrastructure.persistance: info
    org.dormi.learn.infrastructure.persistance.mybatis.MyTenantSqlParser: warn
    org.dormi.learn.infrastructure.persistance.cache: info
