# boostrap存放
# 1. 不能放进nacos的内容

---
spring:
  application:
    name: license-server


---
license:
  product: spaas

---
# 端口和上下文
server:
  port: 8081
  servlet:
    context-path: /member

---
# jackson 序列化
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null

---
# logger
logging:
  level:
    org.springframework: info
    org.springframework.test: info
    org.dormi.learn: debug
    org.dormi.learn.infrastructure.persistance: info
    org.dormi.learn.infrastructure.persistance.mybatis.MyTenantSqlParser: warn
    org.dormi.learn.infrastructure.persistance.cache: info
